### ISSUE TITLE
Error in running fork

### ISSUE THREAD

**Issue by SirMathhman** [isamu-isozaki/tranquility-utility#3]
When cloning the repository and tranq.json is supplied, this error is thrown. Probably due to a change or compilation issue?

```
Uncaught ReferenceError: m is not defined
    at start (tranq.js:341)
    at HTMLButtonElement.onclick (tranq.html:12)
```

**Comment by isamu-isozaki** [comment]
Hi! Thanks for reporting this issue. I made it so that when the Html name does not match the JSON name like with tranq.html, hello.json is used by default with the newest commit. I'm going to close this issue now but if the issue persists, please reopen it.
